// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaMantencion.Data;

#nullable disable

namespace SistemaMantencion.Migrations
{
    [DbContext(typeof(MantencionDbContext))]
    [Migration("20251126012320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SistemaMantencion.Models.Camioneta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaUltimaMantencion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Patente")
                        .IsUnique();

                    b.ToTable("Camionetas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2022,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2025, 11, 25, 22, 23, 19, 668, DateTimeKind.Local).AddTicks(5647),
                            Kilometraje = 15000,
                            Marca = "Toyota",
                            Modelo = "Hilux",
                            Patente = "ABCD12"
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2023,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2025, 11, 25, 22, 23, 19, 668, DateTimeKind.Local).AddTicks(5651),
                            Kilometraje = 8000,
                            Marca = "Ford",
                            Modelo = "Ranger",
                            Patente = "EFGH34"
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2021,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2025, 11, 25, 22, 23, 19, 668, DateTimeKind.Local).AddTicks(5654),
                            Kilometraje = 25000,
                            Marca = "Chevrolet",
                            Modelo = "Colorado",
                            Patente = "IJKL56"
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2022,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2025, 11, 25, 22, 23, 19, 668, DateTimeKind.Local).AddTicks(5693),
                            Kilometraje = 18000,
                            Marca = "Nissan",
                            Modelo = "Frontier",
                            Patente = "MNOP78"
                        },
                        new
                        {
                            Id = 5,
                            Anio = 2023,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2025, 11, 25, 22, 23, 19, 668, DateTimeKind.Local).AddTicks(5696),
                            Kilometraje = 5000,
                            Marca = "Mitsubishi",
                            Modelo = "L200",
                            Patente = "QRST90"
                        });
                });

            modelBuilder.Entity("SistemaMantencion.Models.HistorialCamioneta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CamionetaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EstadoAnterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoNuevo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KilometrajeAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KilometrajeNuevo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CamionetaId");

                    b.ToTable("Historial");
                });

            modelBuilder.Entity("SistemaMantencion.Models.RegistroMantencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CamionetaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometrajeRegistrado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMantencion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CamionetaId");

                    b.ToTable("Mantenciones");
                });

            modelBuilder.Entity("SistemaMantencion.Models.HistorialCamioneta", b =>
                {
                    b.HasOne("SistemaMantencion.Models.Camioneta", "Camioneta")
                        .WithMany()
                        .HasForeignKey("CamionetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camioneta");
                });

            modelBuilder.Entity("SistemaMantencion.Models.RegistroMantencion", b =>
                {
                    b.HasOne("SistemaMantencion.Models.Camioneta", "Camioneta")
                        .WithMany("Mantenciones")
                        .HasForeignKey("CamionetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camioneta");
                });

            modelBuilder.Entity("SistemaMantencion.Models.Camioneta", b =>
                {
                    b.Navigation("Mantenciones");
                });
#pragma warning restore 612, 618
        }
    }
}
